title: yea
author: water900
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  e

# social links
twitter_username: your-twitter-handle
github_username:  water900

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
